// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test} from "forge-std/Test.sol";
import {Engine} from "../src/Engine.sol";

/// Writes web/research.js: the cost table and the check of the error bar.
/// Nothing on the page is typed by hand.
contract AuditTest is Test {
    Engine e;
    uint256 constant SPOT = 100e18;

    function setUp() public { e = new Engine(); }

    function u(uint256 v) internal pure returns (string memory) { return vm.toString(v); }

    function bursty(Engine.Payoff pay, uint16 paths, uint256 seed) internal pure returns (Engine.Spec memory s) {
        uint256 v = 4e12; uint256 a = 0.2166e18; uint256 b = 0.7293e18;
        s = Engine.Spec(pay, SPOT, SPOT, v, (v * (1e18 - a - b)) / 1e18, a, b, 78, 3, paths, seed);
    }

    function test_WriteEverything() public {
        string memory j = "{\n";
        j = string.concat(j, ' "spec": {"steps": 78, "every": 3, "passes": 5, "spot": ', u(SPOT), '},\n');

        // ---- cost ----
        j = string.concat(j, ' "gas": [\n');
        uint16[4] memory P = [uint16(32), 64, 96, 128];
        for (uint256 i; i < P.length; ++i) {
            uint256 g = gasleft(); e.quote(bursty(Engine.Payoff.Call, P[i], 1)); uint256 gv = g - gasleft();
            g = gasleft(); e.quote(bursty(Engine.Payoff.AsianCall, P[i], 1)); uint256 ga = g - gasleft();
            j = string.concat(j, '  {"paths": ', u(P[i]), ', "vanilla": ', u(gv), ', "asian": ', u(ga), '}', i == 3 ? '\n' : ',\n');
        }
        j = string.concat(j, ' ],\n');

        // ---- the error bar, checked against a closed form ----
        string memory ref = vm.readFile("data/reference.json");
        uint256 v = vm.parseJsonUint(ref, ".varStep");
        j = string.concat(j, ' "calibration": [\n');
        j = string.concat(j, calib("call, strike 100", Engine.Spec(Engine.Payoff.Call, SPOT, 100e18, v, v, 0, 0, 78, 1, 128, 0), vm.parseJsonUint(ref, ".call100")), ',\n');
        j = string.concat(j, calib("call, strike 102", Engine.Spec(Engine.Payoff.Call, SPOT, 102e18, v, v, 0, 0, 78, 1, 128, 0), vm.parseJsonUint(ref, ".call102")), ',\n');
        j = string.concat(j, calib("put, strike 98", Engine.Spec(Engine.Payoff.Put, SPOT, 98e18, v, v, 0, 0, 78, 1, 128, 0), vm.parseJsonUint(ref, ".put98")), '\n');
        j = string.concat(j, ' ]\n}\n');

        vm.writeFile("web/research.js", string.concat("// Generated by test/Audit.t.sol; do not hand-edit.\nexport default ", j));
    }

    /// A hundred quotes of 128 paths: their mean against the closed form, the
    /// error they report against the spread they actually show.
    function calib(string memory label, Engine.Spec memory s, uint256 exact) internal view returns (string memory) {
        uint256 n = 100; uint256 sum; uint256 sq; uint256 seSum;
        for (uint256 k = 1; k <= n; ++k) {
            s.seed = k;
            (uint256 m, uint256 se) = e.quote(s);
            sum += m; sq += m * m; seSum += se;
        }
        uint256 mean = sum / n;
        uint256 spread = isqrt(((sq / n - mean * mean) * n) / (n - 1));
        uint256 seAvg = seSum / n;
        uint256 gap = mean > exact ? mean - exact : exact - mean;
        assertLt(gap, 3 * (seAvg / 10), "mean off the closed form");
        return string.concat('  {"contract": "', label, '", "exact": ', u(exact), ', "mean": ', u(mean),
            ', "reportedSe": ', u(seAvg), ', "observedSpread": ', u(spread),
            ', "gapInSeOfMeanBps": ', u((gap * 1e4) / (seAvg / 10)), ', "quotes": 100, "paths": 128}');
    }

    function isqrt(uint256 x) internal pure returns (uint256 y) {
        if (x == 0) return 0;
        y = x; uint256 k = (x >> 1) + 1;
        while (k < y) { y = k; k = (x / k + k) >> 1; }
    }
}
