// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test, console} from "forge-std/Test.sol";
import {Engine} from "../src/Engine.sol";
import {Live} from "../src/Live.sol";
import {Feeds} from "../src/Feeds.sol";

/// Against the chain itself, at a fixed block.
contract LiveForkTest is Test {
    uint256 constant BLOCK = 67367297;
    Live live;
    uint256 forkBlock;

    function setUp() public {
        vm.createSelectFork(vm.rpcUrl("hood"), vm.envOr("BLOCK", BLOCK)); // BLOCK=<n> to rerun at another block
        forkBlock = block.number;
        live = new Live(new Engine(), Feeds.all());
    }

    function test_CadenceOnEveryFeed() public view {
        Live.Feed[] memory f = live.feeds();
        for (uint256 i; i < f.length; ++i) {
            (uint256 v, uint256 thr, uint256 prints, uint256 secs) = live.cadence(i, 64);
            console.log(f[i].symbol, "sd per step (bps)", isqrt(v * 1e18) / 1e14, "threshold (bps)");
            console.log("   ", thr / 1e14, "prints / trading seconds", prints);
            console.log("   ", secs);
            assertGt(thr, 0.002e18, "threshold below 20 bps is not a real deviation feed");
            assertLt(thr, 0.02e18, "threshold too large");
        }
    }

    function test_QuoteNvdaAsianAtTheMoney() public view {
        uint256 g = gasleft();
        Live.Result memory r = live.quote(4, Engine.Payoff.AsianCall, 0, 78, 3, 128, 64, 1);
        g -= gasleft();
        console.log("NVDA spot", r.spot, "feed updated at", r.updatedAt);
        console.log("asian call, at the money, one session:", r.mean, "+-", r.se);
        console.log("gas for the whole live quote", g);
        assertLt((r.se * 100) / r.mean, 50, "quote noisier than half the price");
        assertLt(g, 36_000_000, "one live quote must fit under the public node's budget");
    }


    /// Writes web/fork.js: every feed's spot, rhythm and at-the-money quote at the pinned block.
    function test_WriteChainSample() public {
        Live.Feed[] memory f = live.feeds();
        string memory j = string.concat('{\n "block": ', vm.toString(forkBlock), ', "rounds": 64, "paths": 128, "steps": 78, "every": 3,\n "feeds": [\n');
        for (uint256 i; i < f.length; ++i) {
            (uint256 v, uint256 thr, uint256 prints, uint256 secs) = live.cadence(i, 64);
            uint256 g = gasleft();
            Live.Result memory r = live.quote(i, Engine.Payoff.AsianCall, 0, 78, 3, 128, 64, 1);
            g -= gasleft();
            j = string.concat(j, '  {"symbol": "', f[i].symbol, '", "aggregator": "', vm.toString(f[i].aggregator),
                '", "omega": ', vm.toString(f[i].omega), ', "alpha": ', vm.toString(f[i].alpha), ', "beta": ', vm.toString(f[i].beta),
                ', "spot": ', vm.toString(r.spot), ', "updatedAt": ', vm.toString(r.updatedAt),
                ', "varStep": ', vm.toString(v), ', "threshold": ', vm.toString(thr),
                ', "prints": ', vm.toString(prints), ', "tradingSeconds": ', vm.toString(secs),
                ', "asianCall": ', vm.toString(r.mean), ', "se": ', vm.toString(r.se), ', "gas": ', vm.toString(g), '}',
                i == f.length - 1 ? '\n' : ',\n');
        }
        j = string.concat(j, ' ]\n}\n');
        vm.writeFile("web/fork.js", string.concat("// Generated by test/Live.fork.t.sol at a fixed block; do not hand-edit.\nexport default ", j));
    }

    function isqrt(uint256 x) internal pure returns (uint256 y) {
        if (x == 0) return 0;
        y = x; uint256 k = (x >> 1) + 1;
        while (k < y) { y = k; k = (x / k + k) >> 1; }
    }
}
