"""Measures the public node's view-call budget with the real engine and no deployment:
the engine's runtime bytecode is placed at an empty address with eth_call's state
override, and the same Asian quote is asked with more and more paths until the
node refuses. Writes web/budget.js. Needs Foundry's cast and a built out/ directory."""
import json, os, subprocess, datetime
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.join(HERE, "..")
RPC = "https://rpc.mainnet.chain.robinhood.com"
ADDR = "0x00000000000000000000000000000000000E0001"
SIG = "quote((uint8,uint256,uint256,uint256,uint256,uint256,uint256,uint16,uint16,uint16,uint256))(uint256,uint256)"
code = json.load(open(os.path.join(ROOT, "out/Engine.sol/Engine.json")))["deployedBytecode"]["object"]
def ask(paths):
    spec = f"(2,100000000000000000000,100000000000000000000,4000000000000,216400000000,216600000000000000,729300000000000000,78,3,{paths},1)"
    r = subprocess.run(["cast", "call", ADDR, SIG, spec, "--override-code", f"{ADDR}:{code}", "--rpc-url", RPC], capture_output=True, text=True)
    return r.returncode == 0 and "Error" not in r.stdout + r.stderr
block = int(subprocess.run(["cast", "block-number", "--rpc-url", RPC], capture_output=True, text=True).stdout.strip())
lo, hi = 128, 256                      # 128 known to pass; find the first refusal by bisection
assert ask(lo), "128 paths refused"
while ask(hi): lo, hi = hi, hi * 2
while hi - lo > 4:
    mid = (lo + hi) // 2
    if ask(mid): lo = mid
    else: hi = mid
out = {"generatedBy": "tools/budget.py", "date": datetime.date.today().isoformat(), "block": block, "rpc": RPC,
       "quote": "Asian call, 78 steps, every 3, alpha 0.2166, beta 0.7293",
       "largestAnswered": lo, "smallestRefused": hi}
open(os.path.join(ROOT, "web", "budget.js"), "w").write("// Generated by tools/budget.py against the public node; do not hand-edit.\nexport default " + json.dumps(out, indent=1) + "\n")
print(out)
