"""How well the on-chain volatility estimate tracks realized volatility.

Mirrors Live.cadence exactly: windows of 64 consecutive feed rounds, the median
absolute answer change as the threshold, the sum of gaps under 7200 s as trading
time, variance per five-minute step = threshold^2 * prints * 300 / trading time.
Each window is compared with the standard deviation of five-minute bar returns
over the same span. Writes web/cadence.js with the SHA-256 of every input."""
import json, glob, os, math, hashlib, statistics as st
HERE = os.path.dirname(os.path.abspath(__file__)); DATA = os.path.join(HERE, "..", "data")
ROUNDS, GAP, STEP = 64, 7200, 300   # window rounds, session gap in s, five-minute step

def rows(path):
    o = json.load(open(path))
    return o if isinstance(o, list) else [v for v in o.values() if isinstance(v, list)][0]

out = {"generatedBy": "tools/cadence.py", "rounds": ROUNDS, "sessionGap": GAP, "sourceSha256": {}, "tickers": {}, "pooled": {}}
ratios_all = []
for rf in sorted(glob.glob(f"{DATA}/rounds-RH*.json")):
    sym = os.path.basename(rf)[7:-5]; bf = f"{DATA}/bars-{sym}.json"
    for f in (rf, bf): out["sourceSha256"][os.path.basename(f)] = hashlib.sha256(open(f, "rb").read()).hexdigest()
    R = sorted((int(x["updatedAt"]), float(x["answer"])) for x in rows(rf))
    B = sorted(((int(b["t"]), float(b["c"])) for b in rows(bf)))
    ratios = []
    for end in range(ROUNDS + 1, len(R) + 1, ROUNDS):
        w = R[end - ROUNDS - 1:end]
        prints = secs = 0; ch = []
        for (t0, p0), (t1, p1) in zip(w, w[1:]):
            if 0 < t1 - t0 < GAP: secs += t1 - t0; prints += 1
            ch.append(abs(p1 - p0) / p0)
        if secs == 0: continue
        thr = st.median(ch); var_step = thr * thr * prints * STEP / secs
        bb = [b for b in B if w[0][0] <= b[0] <= w[-1][0]]
        rets = [math.log(c1 / c0) for (t0, c0), (t1, c1) in zip(bb, bb[1:]) if 0 < t1 - t0 <= 600]
        if len(rets) < 30: continue
        ratios.append(math.sqrt(var_step) / st.pstdev(rets))
    if ratios:
        q = sorted(ratios)
        out["tickers"][sym[2:]] = {"windows": len(q), "median": st.median(q), "min": q[0], "max": q[-1]}
        ratios_all += ratios
q = sorted(ratios_all)
out["pooled"] = {"windows": len(q), "median": st.median(q), "p10": q[len(q) // 10], "p90": q[9 * len(q) // 10],
                 "withinAThird": sum(1 for r in q if 2 / 3 <= r <= 4 / 3) / len(q)}
open(os.path.join(HERE, "..", "web", "cadence.js"), "w").write("// Generated by tools/cadence.py; do not hand-edit.\nexport default " + json.dumps(out, indent=1) + "\n")
print("wrote web/cadence.js")
for k, v in out["tickers"].items(): print(f"  {k:5s} windows {v['windows']:3d}  median ratio {v['median']:.2f}  range {v['min']:.2f}-{v['max']:.2f}")
print("  pooled:", {k: (round(v, 3) if isinstance(v, float) else v) for k, v in out["pooled"].items()})
