# Regenerate whenever data/garch-fits.json changes.
"""Writes src/Feeds.sol from data/garch-fits.json, the per-ticker GARCH(1,1) fits
published with the intermittency paper (omega in percent squared per five-minute
bar; alpha, beta dimensionless), and the aggregators of the feeds they were fitted on."""
import json, os, hashlib, subprocess
HERE = os.path.dirname(os.path.abspath(__file__))
FITS = os.path.join(HERE, "..", "data", "garch-fits.json")
AGG = {  # feed aggregators on the chain, as read on 2026-09-19
    "RHAMD":  "0xdad54b8ee51af258e5a6faa9a84a3300f4775f7d",
    "RHINTC": "0x95fb52f75aecbca8e12aa4403f840c8bc18cfbd4",
    "RHMSFT": "0xc3b117f52cf17dd4369eaf5eaf7cf0e2f91b4e30",
    "RHMU":   "0xa088fad0a0a62693af068e2edb80b1578c8a9365",
    "RHNVDA": "0xc9d16e4f2569b9e3ea0468fd85844953713dc2a2",
    "RHSNDK": "0x7b2fdfcea772f093dd33b3acf8ee294b368f6c23",
    "RHSPY":  "0x78bcb218fa04b9b3a278ebc865ed320bf8defbac",
    "RHTSLA": "0x7a6b81ba7fbcb90104d8c496158cf383cd7233b1",
    "RHUSO":  "0xa6ac45e27d19f91c55109191d71cfba4a9f5fbe1",
}
fits = json.load(open(FITS))["fits"]
sha = hashlib.sha256(open(FITS, "rb").read()).hexdigest()
def checksum(a):
    """EIP-55 checksum via cast; the compiler refuses lower-case literals."""
    return subprocess.run(["cast", "to-check-sum-address", a], capture_output=True, text=True, check=True).stdout.strip()
rows = []
for sym, f in sorted(fits.items()):
    omega = round(f["omega"] * 1e14)          # %^2 per bar -> fraction^2 per bar, 1e18
    alpha, beta = round(f["alpha"] * 1e18), round(f["beta"] * 1e18)
    rows.append(f'        f[{len(rows)}] = Live.Feed({checksum(AGG[sym])}, "{sym[2:]}", {omega}, {alpha}, {beta});')
out = f"""// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {{Live}} from "./Live.sol";

/// Generated by tools/feeds.py from data/garch-fits.json (sha256 {sha}).
/// Do not hand-edit.
library Feeds {{
    function all() internal pure returns (Live.Feed[] memory f) {{
        f = new Live.Feed[]({len(rows)});
{chr(10).join(rows)}
    }}
}}
"""
open(os.path.join(HERE, "..", "src", "Feeds.sol"), "w").write(out)
print("wrote src/Feeds.sol with", len(rows), "feeds")
