"""Fits SpaceX the way the nine feeds of the paper were fitted and writes
src/SpaceX.sol: GARCH(1,1) by maximum likelihood on five-minute bars
(data/bars-RHSPCX.json, from the listing onward), omega in percent squared per
bar, alpha and beta dimensionless, then the same unit conversion as
tools/feeds.py. Rerun after refreshing the bars.

    python3 tools/spacex.py
"""
import json, os, hashlib, subprocess
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
BARS = os.path.join(HERE, "..", "data", "bars-RHSPCX.json")
FIT = os.path.join(HERE, "..", "data", "garch-fit-spacex.json")
AGG = "0x5eaa223c585f40cdca2d119ea91b97c491245631"   # Robinhood SPCX / USD, read on 2026-09-22
PCT = 100.0


def returns():
    b = json.load(open(BARS))["bars"]
    c = np.array([x["c"] for x in b], float); t = np.array([x["t"] for x in b], float)
    r = np.diff(c) / c[:-1] * PCT
    return r[np.diff(t) <= np.median(np.diff(t)) * 1.5]


def nll(params, r):
    w, a, b = np.exp(params)
    if a + b >= 0.999: return 1e12
    v = np.empty(len(r)); v[0] = r.var()
    for i in range(1, len(r)):
        v[i] = w + a * r[i - 1] ** 2 + b * v[i - 1]
    if not np.all(np.isfinite(v)) or np.any(v <= 0): return 1e12
    return 0.5 * np.sum(np.log(v) + r ** 2 / v)


def nelder_mead(f, x0, r, iters=1200):
    n = len(x0)
    simplex = [np.array(x0, float)]
    for i in range(n):
        p = np.array(x0, float); p[i] += 0.5; simplex.append(p)
    vals = [f(p, r) for p in simplex]
    for _ in range(iters):
        order = np.argsort(vals); simplex = [simplex[i] for i in order]; vals = [vals[i] for i in order]
        cen = np.mean(simplex[:-1], axis=0)
        xr = cen + (cen - simplex[-1]); fr = f(xr, r)
        if fr < vals[0]:
            xe = cen + 2 * (cen - simplex[-1]); fe = f(xe, r)
            simplex[-1], vals[-1] = (xe, fe) if fe < fr else (xr, fr)
        elif fr < vals[-2]:
            simplex[-1], vals[-1] = xr, fr
        else:
            xc = cen + 0.5 * (simplex[-1] - cen); fc = f(xc, r)
            if fc < vals[-1]: simplex[-1], vals[-1] = xc, fc
            else:
                for i in range(1, n + 1):
                    simplex[i] = simplex[0] + 0.5 * (simplex[i] - simplex[0]); vals[i] = f(simplex[i], r)
    i = int(np.argmin(vals)); return simplex[i], vals[i]


def main():
    r = returns(); r = r - r.mean()
    x, _ = nelder_mead(nll, np.log([r.var() * 0.05, 0.05, 0.90]), r)
    w, a, b = (float(v) for v in np.exp(x))
    ann = float(np.sqrt(w / (1 - a - b)) * np.sqrt(78 * 252))
    sha = hashlib.sha256(open(BARS, "rb").read()).hexdigest()
    bars = json.load(open(BARS))["bars"]
    fit = {"source": "GARCH(1,1) fit on five-minute bars since the listing, the fitter of the intermittency paper",
           "bars": len(bars), "firstBar": bars[0]["t"], "lastBar": bars[-1]["t"], "returns": int(r.size),
           "sourceSha256": sha, "units": {"omega": "percent squared per five-minute bar", "alpha": "1", "beta": "1"},
           "fit": {"omega": w, "alpha": a, "beta": b, "halfLifeBars": float(np.log(0.5) / np.log(a + b)), "longRunAnnualVolPct": ann}}
    json.dump(fit, open(FIT, "w"), indent=1)
    addr = subprocess.run(["cast", "to-check-sum-address", AGG], capture_output=True, text=True, check=True).stdout.strip()
    omega, alpha, beta = round(w * 1e14), round(a * 1e18), round(b * 1e18)
    out = f"""// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {{Live}} from "./Live.sol";

/// Generated by tools/spacex.py from data/bars-RHSPCX.json (sha256 {sha}):
/// the SpaceX feed on Robinhood Chain with a variance memory fitted the way the
/// nine feeds of the paper were, on five-minute bars since the listing.
/// Do not hand-edit.
library SpaceX {{
    function feed() internal pure returns (Live.Feed memory) {{
        return Live.Feed({addr}, "SPCX", {omega}, {alpha}, {beta});
    }}
}}
"""
    open(os.path.join(HERE, "..", "src", "SpaceX.sol"), "w").write(out)
    print(f"SPCX  omega {w:.6f}  alpha {a:.4f}  beta {b:.4f}  a+b {a+b:.4f}  half life {fit['fit']['halfLifeBars']:.1f} bars  long-run vol {ann:.1f}%  ({r.size} returns)")


if __name__ == "__main__":
    main()
