// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Live} from "./Live.sol";

/// Generated by tools/spacex.py from data/bars-RHSPCX.json (sha256 5eef646497deb8889c1c3f156ee6914a02686cb396009cbedbe5ef70b237271a):
/// the SpaceX feed on Robinhood Chain with a variance memory fitted the way the
/// nine feeds of the paper were, on five-minute bars since the listing.
/// Do not hand-edit.
library SpaceX {
    function feed() internal pure returns (Live.Feed memory) {
        return Live.Feed(0x5eaa223c585F40CDcA2D119ea91B97C491245631, "SPCX", 922859080855, 232393648806321824, 729956665999775744);
    }
}
