// Generated by tools/budget.py against the public node; do not hand-edit.
export default {
 "generatedBy": "tools/budget.py",
 "date": "2026-09-20",
 "block": 67373533,
 "rpc": "https://rpc.mainnet.chain.robinhood.com",
 "quote": "Asian call, 78 steps, every 3, alpha 0.2166, beta 0.7293",
 "largestAnswered": 184,
 "smallestRefused": 188
}
