// Generated by tools/cadence.py; do not hand-edit.
export default {
 "generatedBy": "tools/cadence.py",
 "rounds": 64,
 "sessionGap": 7200,
 "sourceSha256": {
  "rounds-RHAMD.json": "dedf438bbb25359fdd30c3f1af87e12b4cfb9566351d64929b2d4aa3e93256d5",
  "bars-RHAMD.json": "fd3a8636621389597be9297d169eb3399763835564e09d231402cb1528e080ce",
  "rounds-RHINTC.json": "5bf5464b9d8aff7243a1d25180820d29129e551d83c769fbb9a489b2ce543668",
  "bars-RHINTC.json": "ddcd04b3a6ea9de340fcd7877d4a49a1de17a8d148240876aba0c2128c564f6b",
  "rounds-RHMSFT.json": "bf47ad3c5b3113090e600d60c5fb6f7660e2b5a1e520706bd91c2b98c3d62d1a",
  "bars-RHMSFT.json": "1c0e52b75fcf74b060594ea352206f425b88228e5566e7b318f7b2606f690b34",
  "rounds-RHMU.json": "c034167d79ddab1ae0e75f37e54dff7ff79c751d1252c9304418a16bde28e151",
  "bars-RHMU.json": "c657504c882474eff74f6cbe6b1d658c1474773f14995a001d0a55a9e2c08f1f",
  "rounds-RHNVDA.json": "5e0a410b5ec5619f33c4e2dc7a4bfca424a19a41a3993b7bb525ece447bb858b",
  "bars-RHNVDA.json": "d914b88c2bb8b77eec6f4f46b13a34ad2b3718e8cb2db07198d8b94c36f4af37",
  "rounds-RHSNDK.json": "f1e84577ccb41a40497953c27d34d62c1a521dc043add4c72d698de96edf8ce8",
  "bars-RHSNDK.json": "b41d2374f1f5f0ba0e3f5728fad046eda800ad3b1a9b23f8b6a4d04de2040553",
  "rounds-RHSPY.json": "f28d4a63b7f932def8c0ceaae672d65ed64c420eb03746318a8b2625ceff89a3",
  "bars-RHSPY.json": "5cbb7dc2b607ae942977db9bc415a8d101106e029515d0603489e4079214c83c",
  "rounds-RHTSLA.json": "666755fed043ce9f8465c4195657aee76896857ae1762904272066f8b4ff23e6",
  "bars-RHTSLA.json": "2ed7c2b4c5ab2506748b3a41bab8fc65361811c1820e0c2ea64e642da6a20eeb",
  "rounds-RHUSO.json": "f456aa3e1a1b4fc140240f08da5acbeaa78b71036df39c6bc6f8fa936efd1870",
  "bars-RHUSO.json": "b2f7098df6884d898689cd7425245ba4dbb3af29e46f97c8ea9f88ee455946c8"
 },
 "tickers": {
  "AMD": {
   "windows": 41,
   "median": 0.8299721165256653,
   "min": 0.5604946633546896,
   "max": 2.3339672968977108
  },
  "INTC": {
   "windows": 52,
   "median": 0.8483143573155707,
   "min": 0.45214920734475045,
   "max": 2.0437136519446266
  },
  "MSFT": {
   "windows": 10,
   "median": 1.2195125649891336,
   "min": 0.929800508992767,
   "max": 1.499559167360381
  },
  "MU": {
   "windows": 52,
   "median": 0.8504027164943482,
   "min": 0.5271727533698858,
   "max": 1.3367579895714612
  },
  "NVDA": {
   "windows": 16,
   "median": 1.0393621083043512,
   "min": 0.8093851969579835,
   "max": 1.4050552734548871
  },
  "SNDK": {
   "windows": 57,
   "median": 0.8352832010944574,
   "min": 0.5401032159820234,
   "max": 1.1562582646532311
  },
  "SPY": {
   "windows": 1,
   "median": 2.0338812094359384,
   "min": 2.0338812094359384,
   "max": 2.0338812094359384
  },
  "TSLA": {
   "windows": 18,
   "median": 0.9824899603569489,
   "min": 0.7363491271464802,
   "max": 1.288255882423858
  },
  "USO": {
   "windows": 22,
   "median": 1.1147985966964447,
   "min": 0.8276419519159914,
   "max": 1.3908652119624936
  }
 },
 "pooled": {
  "windows": 269,
  "median": 0.8807992033162959,
  "p10": 0.6467358326468018,
  "p90": 1.1933628843043544,
  "withinAThird": 0.8364312267657993
 }
}
