// Generated by test/Audit.t.sol; do not hand-edit.
export default {
 "spec": {"steps": 78, "every": 3, "passes": 5, "spot": 100000000000000000000},
 "gas": [
  {"paths": 32, "vanilla": 5877868, "asian": 8593580},
  {"paths": 64, "vanilla": 11732884, "asian": 17186841},
  {"paths": 96, "vanilla": 17585358, "asian": 25732074},
  {"paths": 128, "vanilla": 23439861, "asian": 34273778}
 ],
 "calibration": [
  {"contract": "call, strike 100", "exact": 704663403358438272, "mean": 700822094658882579, "reportedSe": 90661528234545886, "observedSpread": 93930730838380282, "gapInSeOfMeanBps": 4236, "quotes": 100, "paths": 128},
  {"contract": "call, strike 102", "exact": 117387814559020144, "mean": 112157698483867251, "reportedSe": 34493627771300881, "observedSpread": 31510022189606956, "gapInSeOfMeanBps": 15162, "quotes": 100, "paths": 128},
  {"contract": "put, strike 98", "exact": 109964625072322512, "mean": 107381964954078448, "reportedSe": 32796984982115208, "observedSpread": 33621615384360639, "gapInSeOfMeanBps": 7874, "quotes": 100, "paths": 128}
 ]
}
